# Generated by Django 3.1.3 on 2020-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='data',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='texto',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='titulo',
            field=models.CharField(default='', editable=False, help_text='Entre com o titulo', max_length=100),
        ),
    ]
