# Generated by Django 3.1.3 on 2020-11-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0003_auto_20201122_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='texto',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arquivo',
            field=models.CharField(default='', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='data',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='titulo',
            field=models.CharField(default='', editable=False, help_text='Entre com o titulo', max_length=100),
        ),
    ]
