# Generated by Django 3.1.3 on 2020-11-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_auto_20201126_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(default='', max_length=1000)),
                ('data', models.CharField(default='', max_length=10, verbose_name='Data de nascimento')),
                ('titulo', models.CharField(default='', help_text='Entre com o titulo', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(default='', max_length=1000, upload_to=''),
        ),
    ]
