# Generated by Django 3.1.3 on 2020-11-28 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0005_auto_20201126_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
        migrations.AlterField(
            model_name='texto',
            name='data',
            field=models.CharField(default='', max_length=10, verbose_name='Data de criação'),
        ),
    ]
