# Generated by Django 3.1.3 on 2020-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0006_auto_20201128_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='conteudo',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
