# Generated by Django 3.1.3 on 2020-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0007_auto_20201129_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='conteudo',
            field=models.TextField(default=''),
        ),
    ]
