# Generated by Django 3.1.3 on 2020-11-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0009_auto_20201130_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texto',
            name='data',
            field=models.CharField(default='', max_length=30, verbose_name='Data de criação'),
        ),
    ]
